// The station's musical FAMILIES.
//
// A family is not a preset of tempo and key. It is a bundle of four
// independent grammars — harmonic, rhythmic, instrumental and structural —
// that together give a track an identity a listener can name ("that's the
// guitar one", "that's the late-night one"). The previous radio varied only
// tempo/key/swing on top of ONE bundle, which is why twelve "tracks" read as
// one backing track.
//
// Rules that keep the set honest, asserted by tests/radio-music.test.mjs:
//   * at least 8 families
//   * no two families share the same (groove, chordStyle, bassStyle) triple
//   * the families between them use at least 6 of the 8 harmonic grammars
//   * the families between them use at least 6 distinct rhythmic grammars

export const FAMILIES = [
  {
    id: 'brightPop',
    label: 'Bright pop-rock',
    energy: 'up',
    bpm: [112, 128],
    scales: ['major'],
    grammars: [['popFunctional', 3], ['bluesBased', 1]],
    groove: 'straight8',
    swing: [0, 0.02],
    kit: { snare: 'snare', hat: 'hat', extra: 'tamb' },
    chordVoice: 'egtr', chordStyle: 'strum', chordCenter: 60,
    padVoice: 'organ', padLevel: 0.16,
    bassVoice: 'fbass', bassStyle: 'melodic',
    leadVoice: 'egtr', leadStyle: 'hook', leadCenter: 74,
    density: 0.85,
    structure: 'pop',
    duration: [155, 235],
  },
  {
    id: 'softAC',
    label: 'Soft adult contemporary',
    energy: 'calm',
    bpm: [76, 92],
    scales: ['major'],
    grammars: [['popFunctional', 2], ['rnbExtended', 1]],
    groove: 'ballad',
    swing: [0, 0.04],
    kit: { snare: 'rim', hat: 'hat', extra: null },
    chordVoice: 'ep', chordStyle: 'pad', chordCenter: 60,
    padVoice: 'strings', padLevel: 0.2,
    bassVoice: 'fbass', bassStyle: 'halfnote',
    leadVoice: 'piano', leadStyle: 'phrase', leadCenter: 72,
    density: 0.5,
    structure: 'ballad',
    duration: [190, 300],
  },
  {
    id: 'funk',
    label: 'Funk / groove',
    energy: 'groove',
    bpm: [98, 112],
    scales: ['dorian', 'mixolydian'],
    grammars: [['modalVamp', 3], ['bluesBased', 1]],
    groove: 'straight16',
    swing: [0.02, 0.08],
    kit: { snare: 'snare', hat: 'hat', extra: 'shaker' },
    chordVoice: 'clav', chordStyle: 'pulse16', chordCenter: 62,
    padVoice: null, padLevel: 0,
    bassVoice: 'fbass', bassStyle: 'sync16',
    leadVoice: 'clav', leadStyle: 'riff', leadCenter: 74,
    density: 0.95,
    structure: 'vamp',
    duration: [165, 250],
  },
  {
    id: 'newWave',
    label: 'New-wave / synth-pop',
    energy: 'up',
    bpm: [118, 134],
    scales: ['minor', 'dorian'],
    grammars: [['newWaveSteps', 3], ['minorPop', 2]],
    groove: 'fourfloor',
    swing: [0, 0],
    kit: { snare: 'clap', hat: 'ohat', extra: null },
    chordVoice: 'synpad', chordStyle: 'stab', chordCenter: 64,
    padVoice: 'synpad', padLevel: 0.18,
    bassVoice: 'synbass', bassStyle: 'pump',
    leadVoice: 'lead', leadStyle: 'hook', leadCenter: 76,
    density: 0.9,
    structure: 'pop',
    duration: [160, 240],
  },
  {
    id: 'rnb',
    label: 'R&B groove',
    energy: 'groove',
    bpm: [86, 100],
    scales: ['major', 'dorian'],
    grammars: [['rnbExtended', 3], ['jazzCycle', 1]],
    groove: 'swing16',
    swing: [0.10, 0.18],
    kit: { snare: 'snare', hat: 'hat', extra: 'shaker' },
    chordVoice: 'ep', chordStyle: 'comp', chordCenter: 60,
    padVoice: 'strings', padLevel: 0.12,
    bassVoice: 'fbass', bassStyle: 'melodic',
    leadVoice: 'ep', leadStyle: 'phrase', leadCenter: 72,
    density: 0.7,
    structure: 'extended',
    duration: [180, 280],
  },
  {
    id: 'acousticPop',
    label: 'Acoustic pop',
    energy: 'medium',
    bpm: [96, 116],
    scales: ['major'],
    grammars: [['popFunctional', 3], ['minorPop', 1]],
    groove: 'acoustic',
    swing: [0, 0.03],
    kit: { snare: 'snare', hat: 'shaker', extra: 'tamb' },
    chordVoice: 'agtr', chordStyle: 'arp', chordCenter: 59,
    padVoice: null, padLevel: 0,
    bassVoice: 'fbass', bassStyle: 'melodic',
    leadVoice: 'agtr', leadStyle: 'phrase', leadCenter: 73,
    density: 0.65,
    structure: 'pop',
    duration: [165, 245],
  },
  {
    id: 'soundtrack',
    label: 'Instrumental soundtrack',
    energy: 'calm',
    bpm: [70, 88],
    scales: ['lydian', 'major', 'minor'],
    grammars: [['cinematicDrift', 3], ['modalVamp', 1]],
    groove: 'halftime',
    swing: [0, 0],
    kit: { snare: 'rim', hat: 'shaker', extra: null },
    chordVoice: 'piano', chordStyle: 'arp', chordCenter: 62,
    padVoice: 'strings', padLevel: 0.28,
    bassVoice: 'fbass', bassStyle: 'halfnote',
    leadVoice: 'bell', leadStyle: 'phrase', leadCenter: 79,
    density: 0.4,
    structure: 'ballad',
    duration: [195, 312],
  },
  {
    id: 'jazzPop',
    label: 'Light jazz-pop',
    energy: 'medium',
    bpm: [84, 104],
    scales: ['major'],
    grammars: [['jazzCycle', 3], ['rnbExtended', 1]],
    groove: 'brushed',
    swing: [0.14, 0.22],
    kit: { snare: 'brush', hat: 'ride', extra: null },
    chordVoice: 'ep', chordStyle: 'comp', chordCenter: 61,
    padVoice: null, padLevel: 0,
    bassVoice: 'fbass', bassStyle: 'walk',
    leadVoice: 'marimba', leadStyle: 'phrase', leadCenter: 74,
    density: 0.6,
    structure: 'jazzform',
    duration: [175, 265],
  },
  {
    id: 'retroRock',
    label: 'Retro rock',
    energy: 'up',
    bpm: [120, 142],
    scales: ['mixolydian', 'major'],
    grammars: [['bluesBased', 3], ['popFunctional', 1]],
    groove: 'shuffle',
    swing: [0.16, 0.24],
    kit: { snare: 'snare', hat: 'ride', extra: null },
    chordVoice: 'dgtr', chordStyle: 'stab', chordCenter: 55,
    padVoice: 'organ', padLevel: 0.2,
    bassVoice: 'fbass', bassStyle: 'root',
    leadVoice: 'dgtr', leadStyle: 'riff', leadCenter: 71,
    density: 0.9,
    structure: 'pop',
    duration: [150, 220],
  },
  {
    id: 'dreamPop',
    label: 'Dreamy late-night pop',
    energy: 'low',
    bpm: [66, 82],
    scales: ['minor', 'dorian', 'major'],
    grammars: [['minorPop', 2], ['cinematicDrift', 2], ['modalVamp', 1]],
    groove: 'pushPop',
    swing: [0.06, 0.12],
    kit: { snare: 'rim', hat: 'hat', extra: null },
    chordVoice: 'synpad', chordStyle: 'pad', chordCenter: 63,
    padVoice: 'synpad', padLevel: 0.26,
    bassVoice: 'synbass', bassStyle: 'halfnote',
    leadVoice: 'ep', leadStyle: 'phrase', leadCenter: 75,
    density: 0.42,
    structure: 'ballad',
    duration: [200, 312],
  },
];

export const FAMILY_BY_ID = Object.fromEntries(FAMILIES.map(f => [f.id, f]));

/** Coarse energy buckets the station scheduler programmes against. */
export const ENERGY_ORDER = ['low', 'calm', 'medium', 'groove', 'up'];
export const energyRank = (e) => ENERGY_ORDER.indexOf(e);
