// YOUTUBE STATIONS — GENERATED by scripts/radio/build-stations.mjs. Do not hand-edit.
//
// EVERY ENTRY IS A RECORDING, NOT A VIDEO. A station used to be a list of
// YouTube PLAYLIST ids, which meant the store played whatever somebody else
// had collected — official music videos with skits, lyric videos, hour-long
// mixes. That is why the shop speaker was reported playing car engines and
// gunshots between songs, and no player setting could have fixed it.
//
// So each station now names its recordings individually. Every id below was
// selected by scripts/radio/classify.mjs and then confirmed against YouTube's
// own oEmbed, which is public, documented and key-free — no API key is used
// anywhere in this pipeline, by standing constraint.
//
// The bar each track cleared:
//   - no video marker anywhere in the title ("Official Video", "Lyrics", …)
//   - no performance marker in its annotations ("Live at …", "Concert", …)
//   - POSITIVE evidence that it is audio: an "Artist - Topic" Art Track
//     (label-delivered audio by construction), an "(Official Audio)" or
//     "(Remaster)" annotation, or a bare title on the artist's own channel.
//     The absence of the word "video" was never accepted as evidence.
//
// A track that could not clear that bar was DROPPED. Stations here are
// shorter than the playlists they replace, and that is the intended trade:
// never use a music video as filler.
//
// Regenerate:  node scripts/radio/resolve-audio.mjs && node scripts/radio/build-stations.mjs
// Provenance:  qa/radio-audio.json  (what was asked, what was rejected, why)

export const YT_STATIONS = [
  {
    id: 'blockbuster',
    label: '★ BLOCKBUSTER THROWBACK',
    isDefault: true,
    covers: ['80s', '90s', 'MTV-era'],
    tracks: [
      // a-ha — Take On Me  ·  "Take on Me (2016 Remaster)" [a-ha - Topic]
      'NaQ083rNUwc',
      // Toto — Africa  ·  "Africa" [Toto - Topic]
      'aCFLgavufaY',
      // Fleetwood Mac — Dreams  ·  "Fleetwood Mac - Dreams (Official Audio)" [Fleetwood Mac]
      'PgagPdVM7bk',
      // Tears For Fears — Everybody Wants To Rule The World  ·  "Everybody Wants To Rule The World (Single Version)" [Tears For Fears - Topic]
      'Y7KaPujdBCQ',
      // Bon Jovi — Livin' On A Prayer  ·  "Livin' On A Prayer" [Release - Topic]
      'LhbEZHxnL08',
      // Whitney Houston — I Wanna Dance With Somebody  ·  "I Wanna Dance With Somebody (Who Loves Me) (Single Version)" [Whitney Houston - Topic]
      '2dzf4T3RbEc',
      // Michael Jackson — Billie Jean  ·  "Billie Jean" [Release - Topic]
      'cDu__D7XtHc',
      // Prince — Kiss  ·  "Kiss" [Prince - Topic]
      '-a9kOCHYZIw',
      // Cyndi Lauper — Girls Just Want To Have Fun  ·  "Girls Just Want To Have Fun (Album Version)" [Cyndi Lauper - Topic]
      '9ENP7NOB4Lg',
      // The Police — Every Breath You Take  ·  "Every Breath You Take (Remastered 2023)" [The Police - Topic]
      'XCK8HwF6mvo',
      // Eurythmics — Sweet Dreams (Are Made Of This)  ·  "Sweet Dreams (Are Made of This) [2018 Remastered]" [Eurythmics - Topic]
      'mZxwGnOz7ZQ',
      // Talking Heads — Once In A Lifetime  ·  "Talking Heads - Once In A Lifetime (Official Audio)" [Talking Heads]
      'fR0jgT9UX0Q',
      // INXS — Never Tear Us Apart  ·  "Never Tear Us Apart" [INXS - Topic]
      'qlG16vQw0tc',
      // Peter Gabriel — Sledgehammer  ·  "Sledgehammer" [Peter Gabriel - Topic]
      'D6I9MD7IExY',
      // Kate Bush — Running Up That Hill  ·  "Kate Bush - Running Up That Hill (A Deal With God) (Audio)" [The Sensual World of Kate Bush]
      'Cj5zLX63_4c',
      // Duran Duran — Hungry Like The Wolf  ·  "Hungry Like the Wolf (2001 Remaster)" [Duran Duran - Topic]
      'yLrF5j7up9Q',
      // Phil Collins — In The Air Tonight  ·  "Phil Collins - In The Air Tonight [Audio HQ] HD" [Phil Collins Music]
      'mpYzO6bZMTs',
      // Queen — Under Pressure  ·  "Under Pressure (Remastered 2011)" [This Is Queen]
      'XuY8Ck7-7z8',
      // Madonna — Like A Prayer  ·  "Madonna - Like A Prayer (Audio)" [Madonna CN]
      'lPy9Jmfxe18',
      // George Michael — Faith  ·  "Faith (Remastered 2006)" [George Michael - Topic]
      'N61LHFFfiik',
    ],
  },
  {
    id: 'throwback',
    label: 'THROWBACKS',
    covers: ['Throwbacks', '2000s', '2010s'],
    tracks: [
      // OutKast — Hey Ya!  ·  "Hey Ya!" [OutKast - Topic]
      '-7XnDlYY9qw',
      // Kelly Clarkson — Since U Been Gone  ·  "Since U Been Gone (Jason Nevins Radio Edit)" [Kelly Clarkson - Topic]
      'pNmWeUiZqEE',
      // Nelly Furtado — Say It Right  ·  "Say It Right (Radio Edit)" [Nelly Furtado - Topic]
      'oblDO-N8z_g',
      // MGMT — Kids  ·  "Kids" [MGMT - Topic]
      'DngxJlZSpPo',
      // Kings of Leon — Use Somebody  ·  "Use Somebody (By Kings Of Leon)" [Release - Topic]
      'TO9VmrSBq7I',
      // Alicia Keys — No One  ·  "No One" [Alicia Keys - Topic]
      'eHlBrYz-PQc',
      // Beyoncé — Crazy In Love  ·  "Beyoncé- Crazy In Love ft Jay-Z (Audio)" [Beyoncé Knowles]
      'w0-Z8YaI-eY',
      // Justin Timberlake — SexyBack  ·  "SexyBack" [Justin Timberlake - Topic]
      'gfWQ1r6IQrY',
      // Fall Out Boy — Sugar, We’re Goin Down  ·  "Fall Out Boy - Sugar, We're Goin Down (TLA Radio Edit)" [Fall Out Boy]
      '5xH1UE9O09w',
      // Avril Lavigne — Complicated  ·  "Avril Lavigne  -  Complicated (Audio)" [Avril Lavigne Music 2017]
      'E9LvMRGKge0',
      // Sean Paul — Temperature  ·  "Temperature" [Sean Paul - Topic]
      '55wZaTkes1c',
      // Franz Ferdinand — Take Me Out  ·  "Take Me Out" [Franz Ferdinand - Topic]
      '7dfBmjrN5W0',
      // Gorillaz — Feel Good Inc.  ·  "Gorillaz - Feel Good Inc. (Radio Edit)" [Gorillaz Archive]
      'wgijS5hGWHA',
      // Lily Allen — Smile  ·  "Smile" [Lily Allen - Topic]
      'rGDcbQKxY7Q',
      // Nelly — Hot In Herre  ·  "Hot In Herre" [Nelly - Topic]
      'y8vLMHeO_5s',
      // Gwen Stefani — Hollaback Girl  ·  "Hollaback Girl" [Gwen Stefani - Topic]
      '_jAAixDgHhM',
      // The Black Eyed Peas — I Gotta Feeling  ·  "I Gotta Feeling" [The Black Eyed Peas - Topic]
      'hs_yk24ghzA',
      // Taio Cruz — Dynamite  ·  "Dynamite (Radio Edit)" [Taio Cruz - Topic]
      'C4cdPKLGkhc',
      // The Fray — How To Save A Life  ·  "How to Save a Life (Single Mix)" [The Fray - Topic]
      '5JxUxLXgdyo',
      // Paramore — Misery Business  ·  "Misery Business" [Paramore - Topic]
      'BxiqKGeuL2s',
      // Panic! At The Disco — I Write Sins Not Tragedies  ·  "Panic! At The Disco - I Write Sins Not Tragedies (Remastered)" [Panic! At The Disco]
      '7_zZQazMqrE',
      // Green Day — Boulevard Of Broken Dreams  ·  "Green Day - Boulevard of Broken Dreams (Official Audio)" [Green Day]
      'hBvJyi3fbtA',
      // The Pussycat Dolls — Don’t Cha  ·  "Don't Cha (Radio Edit)" [The Pussycat Dolls - Topic]
      'zYqPmnK_NWc',
      // Estelle — American Boy  ·  "American Boy" [Estelle - Topic]
      'pn2bbcRXdJ4',
      // Adele — Rolling In The Deep  ·  "Adele - Rolling In The Deep" [Adele - Topic]
      'bDtjO-R0QSo',
      // Florence + The Machine — Dog Days Are Over  ·  "Florence + the Machine - Dog Days Are Over" [Florence + the Machine]
      'i8CDxQc_9-E',
      // Two Door Cinema Club — What You Know  ·  "TWO DOOR CINEMA CLUB  | WHAT YOU KNOW" [Two Door Cinema Club]
      'YXwYJyrKK5A',
      // Duffy — Mercy  ·  "Duffy - Mercy (Official HQ Audio)" [DUFFY ARCHIVES]
      'rOu4wwI0xF8',
      // Fergie — Big Girls Don’t Cry  ·  "Big Girls Don't Cry (Personal) (Radio Edit)" [Fergie - Topic]
      'R_vAx6pm1n0',
      // Shaggy — It Wasn’t Me  ·  "Shaggy - It Wasn't Me." [shaggy (alexcho84)]
      '0lqxd2f6BTA',
    ],
  },
  {
    id: 'pop',
    label: 'POP',
    covers: ['Pop'],
    tracks: [
      // Taylor Swift — Blank Space  ·  "Taylor Swift - Blank Space (Audio)" [Taylor Swift Audios]
      '2mIBS3fHp6A',
      // The Weeknd — Blinding Lights  ·  "Blinding Lights" [The Weeknd - Topic]
      'H64a2ggVIWc',
      // Billie Eilish — Bad Guy  ·  "Billie Eilish - bad guy (with Justin Bieber) [Audio]" [Billie Eilish]
      '2pnXjQCegVc',
      // Ed Sheeran — Shape of You  ·  "Ed Sheeran - Shape Of You   (Official Audio)" [Various - Topic]
      'lkeJC8bac9g',
      // Bruno Mars — Treasure  ·  "Treasure" [Bruno Mars - Topic]
      'jz7C2W4m26U',
      // Lorde — Royals  ·  "Lorde - Royals (Audio)" [Lorde]
      'ncgsL1GCFms',
      // Katy Perry — Teenage Dream  ·  "Teenage Dream" [Katy Perry - Topic]
      'JVvvLkwX0ag',
      // Carly Rae Jepsen — Run Away With Me  ·  "Carly Rae Jepsen - Run Away With Me (Audio)" [Carly Rae Jepsen]
      'SSjS6pZ1-pI',
      // Robyn — Dancing On My Own  ·  "Robyn - Dancing On My Own (Official Audio)" [Robyn]
      'WMth6xZlVJU',
      // Olivia Rodrigo — good 4 u  ·  "good 4 u" [Olivia Rodrigo - Topic]
      'aeDdS9aIpck',
      // Justin Bieber — Peaches  ·  "Peaches" [Justin Bieber - Topic]
      'AwYQGtwoF68',
      // Shawn Mendes — Treat You Better  ·  "Shawn Mendes - Treat You Better (Audio)" [Shawn Mendes Audios]
      'eiG_DUXD8YQ',
      // P!nk — Raise Your Glass  ·  "P!nk - Raise Your Glass" [P!NK]
      'l2IkpeeIE4Y',
      // Britney Spears — Toxic  ·  "Britney Spears - Toxic (Audio)" [Britney Jean Spears]
      'ICjG8t_SnSg',
      // Christina Aguilera — Beautiful  ·  "Beautiful (Peter Rauhofer Radio Edit)" [Christina Aguilera - Topic]
      'W_ek8n6H5YM',
      // Adele — Someone Like You  ·  "Adele - Someone Like You" [Adele - Topic]
      '22c3_LoIfZQ',
      // Selena Gomez — Lose You To Love Me  ·  "Lose You To Love Me" [Selena Gomez - Topic]
      'WlA99PPNTik',
      // Little Mix — Shout Out To My Ex  ·  "Shout Out to My Ex" [Little Mix - Topic]
      '4piAcuj0SIg',
      // Demi Lovato — Sorry Not Sorry  ·  "Sorry Not Sorry" [Demi Lovato - Topic]
      '0NYLzP7gbnM',
      // Jonas Brothers — Sucker  ·  "Jonas Brothers - Sucker (Audio)" [Jonas Brothers Fan]
      'HZfy-SZQ6gw',
    ],
  },
  {
    id: 'party',
    label: 'PARTY',
    covers: ['Party'],
    tracks: [
      // Daft Punk — One More Time  ·  "Daft Punk - One More Time (Official Audio)" [Daft Punk]
      'A2VpR8HahKc',
      // Avicii — Levels  ·  "Avicii - Levels (Radio Edit)" [Avicii Music World]
      '8-t268I1XWg',
      // Swedish House Mafia — Don't You Worry Child  ·  "Dont You Worry Child by Swedish House Mafia" [Release - Topic]
      '_SB5sjhTwa4',
      // David Guetta — Titanium  ·  "David Guetta - Titanium (feat. Sia) [Official Audio]" [David Guetta & Sia]
      'Rohq0D72X3Q',
      // LMFAO — Party Rock Anthem  ·  "Party Rock Anthem (Radio Edit)" [LMFAO - Topic]
      'aDon8zy8Bfk',
      // Kylie Minogue — Can't Get You Out Of My Head  ·  "Can't Get You Out of My Head" [Release - Topic]
      '7bOI-SGQxyc',
      // Chic — Le Freak  ·  "Le Freak (2006 Remaster)" [Chic - Topic]
      '7PC-AcrHEKU',
      // KC and the Sunshine Band — Get Down Tonight  ·  "Get Down Tonight (2004 Remaster)" [KC and the Sunshine Band - Topic]
      'tUMk0RbZDZY',
      // Pharrell Williams — Happy  ·  "Pharrell Williams Performs "Happy" Live Apollo Theater" [Pharrell Williams Fans]
      'Bx3CSwg-Jmc',
      // Sister Sledge — We Are Family  ·  "We Are Family (2018 Remaster)" [Sister Sledge - Topic]
      '7LJBmXkB9o8',
      // Donna Summer — Hot Stuff  ·  "Donna Summer - Hot Stuff (Audio)" [Donna Summer]
      'zx0_xHliFNo',
      // Bee Gees — Stayin’ Alive  ·  "Stayin' Alive" [Bee Gees - Topic]
      'aZ5fQyiZgns',
      // Cameo — Word Up!  ·  "Word Up!" [Cameo - Topic]
      'lYOSdI_91WM',
      // Jamiroquai — Canned Heat  ·  "Canned Heat (Remastered 2006)" [Jamiroquai - Topic]
      'Fr1r1KINlvU',
      // Basement Jaxx — Where’s Your Head At  ·  "Where's Your Head At (Radio Edit)" [Basement Jaxx - Topic]
      'ZK2S_DbedRI',
      // Fatboy Slim — Praise You  ·  "Fatboy Slim - Praise You (Official Audio)" [Fatboy Slim]
      '1BoXlv-TV2c',
      // Robin S — Show Me Love  ·  "Show Me Love" [Robin - Topic]
      'WhccJTOVZrM',
      // Crystal Waters — Gypsy Woman  ·  "Gypsy Woman (She's Homeless) (La Da Dee La Da Da) (Strip To The Bone Radio Edit)" [Crystal Waters - Topic]
      'vV6B_P2WgEM',
      // Corona — The Rhythm Of The Night  ·  "The Rhythm Of The Night" [Corona - Topic]
      'QrR_giHTbGI',
    ],
  },
  {
    id: 'rnb',
    label: 'R&B',
    covers: ['R&B'],
    tracks: [
      // Alicia Keys — If I Ain't Got You  ·  "If I Ain't Got You (Radio Edit)" [Alicia Keys - Topic]
      'twYtM7eOSdw',
      // Mary J. Blige — Family Affair  ·  "Family Affair (Radio Edit)" [Mary J. Blige - Topic]
      'XPqg74xDU_4',
      // TLC — Waterfalls  ·  "Waterfalls" [TLC - Topic]
      'R09S7CNPhFs',
      // Destiny’s Child — Say My Name  ·  "Say My Name" [Destiny's Child - Topic]
      'JguQIUGoE3E',
      // En Vogue — Don’t Let Go (Love)  ·  "Don't Let Go (Love) [2012 Remaster]" [En Vogue - Topic]
      'UmBY6Yibnzk',
      // Brandy — The Boy Is Mine  ·  "The Boy Is Mine (Radio Edit with Intro)" [Brandy - Topic]
      'VIOIeQv40JE',
      // Aaliyah — Try Again  ·  "Try Again" [Aaliyah - Topic]
      '8ciOoULvbZc',
      // Toni Braxton — Un-Break My Heart  ·  "Toni Braxton - Un-Break My Heart (Audio)" [The Queen Toni Braxton]
      'ACRMTEzdIrU',
      // Erykah Badu — On & On  ·  "On & On" [Erykah Badu - Topic]
      'TW28iWV7nxE',
      // D’Angelo — Lady  ·  "Lady (Radio Edit)" [D'Angelo - Topic]
      'op4r-yKy1dU',
      // Jill Scott — A Long Walk  ·  "A Long Walk (Remastered)" [Jill Scott - Topic]
      'B6nVV-ibpWk',
      // Musiq Soulchild — Just Friends  ·  "Just Friends" [Release - Topic]
      'o9Ax0jIWy_4',
      // Ne-Yo — So Sick  ·  "So Sick (Radio Edit)" [Ne-Yo - Topic]
      'IPiacfn7H9A',
      // Chris Brown — With You  ·  "With You" [Chris Brown - Topic]
      'sUP-uW07fuA',
      // Monica — Angel Of Mine  ·  "Angel Of Mine as popularized by Monica" [Release - Topic]
      'rOP_5Zem3q8',
      // Keyshia Cole — Love  ·  "Love, I Thought You Had My Back" [Keyshia Cole - Topic]
      'JUEGGPvseYw',
      // Mario — Let Me Love You  ·  "Mario - Let Me Love You (Anniversary Edition) (Audio)" [Mario]
      'Imv2UGGC4wA',
      // Ginuwine — Pony  ·  "Pony" [Ginuwine - Topic]
      'aScuEoqJ36c',
      // Kelly Rowland — Motivation  ·  "Motivation" [Kelly Rowland - Topic]
      'qvnosNwG6s0',
      // Ashanti — Foolish  ·  "Foolish" [Ashanti - Topic]
      '-k2IbLbiDdQ',
      // Amerie — 1 Thing  ·  "1 Thing" [Amerie - Topic]
      'uhQwnqGtEXQ',
      // SWV — Weak  ·  "Weak (Radio Edit)" [SWV - Topic]
      '013SAyWRWLc',
    ],
  },
  {
    id: 'chillrnb',
    label: 'CHILL R&B',
    covers: ['Chill R&B'],
    tracks: [
      // Sade — Smooth Operator  ·  "Smooth Operator (2011 Remastered)" [Sade - Topic]
      'rS7Va0sBYAM',
      // H.E.R. — Focus  ·  "H.E.R. - Focus" [H.E.R.]
      'Uj9y5xkHZaU',
      // Solange — Cranes in the Sky  ·  "Cranes in the Sky" [Release - Topic]
      'PVvAoSI4drc',
      // Jhené Aiko — The Worst  ·  "The Worst" [Jhené Aiko - Topic]
      'zpoAMCwzFBA',
      // Snoh Aalegra — I Want You Around  ·  "Snoh Aalegra - I want you around" [Snoh Aalegra]
      'JdqLKJqlvuc',
      // Brent Faiyaz — Trust  ·  "Brent Faiyaz - TRUST [Official Audio]" [Brent Faiyaz]
      'pa5E4uA3ALY',
      // Cleo Sol — Why Don’t You  ·  "Cleo Sol - Why Don't You (Audio)" [Cleo Sol]
      'SMpMLTpEXVk',
      // Emily King — Distance  ·  "Emily King - Distance" [Emily King]
      'b_jd9l91KdM',
      // India.Arie — Video  ·  "Video (Radio Edit)" [India.Arie - Topic]
      'CEYrHgui_Es',
      // Angie Stone — Wish I Didn’t Miss You  ·  "Wish I Didn't Miss You (Soul Sessions)" [Angie Stone - Topic]
      'xuKxSwwHEDw',
      // Bilal — Soul Sista  ·  "Soul Sista" [Bilal - Topic]
      'AtFd5wtfUdw',
      // Sampha — (No One Knows Me) Like The Piano  ·  "Sampha - (No One Knows Me) Like The Piano (Official Audio)" [Sampha]
      'njHcZMLDdSc',
      // Kali Uchis — Just A Stranger  ·  "Just a Stranger" [Release - Topic]
      'LZ3zMagoX-s',
      // Masego — Tadow  ·  "Masego + FKJ   - Tadow" [Masego]
      'zwf5MpcuKDM',
      // UMI — Remember Me  ·  "Remember Me" [Release - Topic]
      'igLamcDoFT4',
      // Joyce Wrice — On One  ·  "Joyce Wrice - On One Ft. Freddie Gibbs (Official Audio)" [Joyce Wrice]
      'wYI0lB6coL4',
      // dvsn — Too Deep  ·  "dvsn - Too Deep (Official Audio)" [dvsn]
      'N7LBse25QP8',
      // PJ Morton — Say So  ·  "PJ Morton ft. JoJo - Say So (Acoustic Version) (Audio)" [PJ Morton]
      'M0K--YdXw8c',
      // Ravyn Lenae — Skin Tight  ·  "Skin Tight" [Release - Topic]
      'Gc0Nyv5cNM8',
      // Yebba — Distance  ·  "Yebba Raw Vocals ‘Distance’ on the Jean Tour - San Diego CA " [Yebba Updates]
      'dq7wLkp_Z6c',
    ],
  },
  {
    id: 'hiphop',
    label: 'HIP-HOP',
    covers: ['Hip-Hop'],
    tracks: [
      // The Sugarhill Gang — Rapper’s Delight  ·  "Rapper's Delight (7" Single Version)" [The Sugarhill Gang - Topic]
      'A8VkF9gXiwU',
      // Grandmaster Flash — The Message  ·  "The Message (Re-Recorded / Remastered Version)" [Grandmaster Flash - Topic]
      'vMMpm9pLpW4',
      // Run-DMC — It’s Tricky  ·  "It's Tricky" [Run D.M.C. - Topic]
      'f3KnUxhCo3s',
      // Beastie Boys — Intergalactic  ·  "Intergalactic (Edited; Digitally Remastered 2005)" [Beastie Boys - Topic]
      'yUuwPeS2-Aw',
      // Digable Planets — Rebirth of Slick  ·  "Rebirth of Slick (Cool Like Dat)" [Digable Planets - Topic]
      'sVhT7H1jh8Y',
      // Common — The Light  ·  "The Light (Live Album Version (Explicit))" [Common - Topic]
      'xY7vz2N-pxE',
      // Mos Def — Ms. Fat Booty  ·  "Ms. Fat Booty" [Mos Def - Topic]
      'aZvjiLbDQq8',
      // Nas — The World Is Yours  ·  "The World Is Yours (Album Version)" [Nas - Topic]
      'xonW3XNcNkc',
      // Wu-Tang Clan — C.R.E.A.M.  ·  "C.R.E.A.M. (Single Version)" [Wu-Tang Clan - Topic]
      'ecRs1sWZIL4',
      // Fugees — Ready or Not  ·  "Ready or Not" [Fugees - Topic]
      'PWOa_eeKzO0',
      // OutKast — Ms. Jackson  ·  "Ms. Jackson" [OutKast - Topic]
      'oZU9sPQ1lJc',
      // Missy Elliott — Get Ur Freak On  ·  "Get Ur Freak On" [Missy "Misdemeanor" Elliott - Topic]
      'bJe-Gz5Meno',
      // Kanye West — Through The Wire  ·  "Through The Wire" [Kanye West - Topic]
      'AE8y25CcE6s',
      // J. Cole — No Role Modelz  ·  "No Role Modelz" [J. Cole - Topic]
      '8HBcV0MtAQg',
      // Kendrick Lamar — Money Trees  ·  "Money Trees" [Kendrick Lamar - Topic]
      '0nF69UTw99E',
      // Anderson .Paak — Come Down  ·  "Come Down" [Anderson .Paak - Topic]
      'rptBpOCCMWc',
      // Black Star — Definition  ·  "Definition" [Black Star - Topic]
      'uwXqXxDtFYg',
      // Pete Rock & CL Smooth — They Reminisce Over You  ·  "They Reminisce over You (Remastered)" [Pete Rock - Topic]
      'YQbwlwpmrxM',
      // Gang Starr — Above The Clouds  ·  "Above The Clouds" [Gang Starr - Topic]
      '9pNJHDrPAYg',
    ],
  },
  {
    id: 'rap',
    label: 'RAP',
    covers: ['Rap'],
    tracks: [
      // Eminem — Lose Yourself  ·  "Eminem - Lose Yourself (Official Audio)" [Eminem • Songs]
      'i0VyvqSB48k',
      // Jay-Z — Empire State Of Mind  ·  "Jay Z & Alicia Keys perform Empire State of Mind | Tony's Awards 2024" [Jay Z Fan]
      '4whFAehzfiY',
      // Drake — Nice For What  ·  "Nice For What" [Drake - Topic]
      '1Jx4Dv269uE',
      // Kendrick Lamar — HUMBLE.  ·  "HUMBLE." [Kendrick Lamar - Topic]
      'ov4WobPqoSA',
      // Nicki Minaj — Super Bass  ·  "Nicki Minaj - Super Bass (Official Audio)" [Nicki M.]
      'aFwmvQ1pSEc',
      // Cardi B — Bodak Yellow  ·  "Cardi B - Bodak Yellow ( Audio )" [Cardi B]
      'CTU9P19fYM8',
      // Megan Thee Stallion — Savage  ·  "Megan Thee Stallion - Savage [Official Audio]" [Megan Thee Stallion]
      'eJEKHdvntPI',
      // Post Malone — Congratulations  ·  "Post Malone - Congratulations  ft. Quavo (Official Audio)" [Post Malone Musics]
      'm_DG4shGECI',
      // Future — Mask Off  ·  "Mask Off" [Future - Topic]
      'aWb8z-KhZdo',
      // 21 Savage — a lot  ·  "21 Savage - A Lot (Official Audio)" [21 Savage]
      'VbrEsOLu75c',
      // Tyler, The Creator — EARFQUAKE  ·  "EARFQUAKE" [Tyler, The Creator]
      'HmAsUQEFYGI',
      // Lil Wayne — A Milli  ·  "A Milli (Album Version (Edited))" [Lil Wayne - Topic]
      'NdgpcwqBSPg',
      // 50 Cent — In Da Club  ·  "In Da Club" [50 Cent - Topic]
      'z8BYGMdHDQ0',
      // Ludacris — Money Maker  ·  "Money Maker (Album Version (Edited))" [Ludacris - Topic]
      'zmmNVwDk3Dg',
      // T.I. — Whatever You Like  ·  "Whatever You Like" [T.I. - Topic]
      'aSX6rKnPCws',
      // Meek Mill — Dreams and Nightmares  ·  "Dreams and Nightmares" [Meek Mill - Topic]
      'c4iQR8Onifw',
      // Logic — 1-800-273-8255  ·  "Logic - 1-800-273-8255 ft. Alessia Cara & Khalid (Official Audio)" [1-800 Logic]
      '9X-A0e4H_Ro',
    ],
  },
  {
    id: 'country',
    label: 'COUNTRY',
    covers: ['Country'],
    tracks: [
      // Patsy Cline — Crazy  ·  "Crazy (Remastered)" [Patsy Cline - Topic]
      '7PqtUULmZSE',
      // Merle Haggard — Mama Tried  ·  "Mama Tried (Remastered 2001)" [Merle Haggard - Topic]
      'XyRCvukVv6w',
      // George Strait — Amarillo By Morning  ·  "Amarillo By Morning" [George Strait - Topic]
      'FbVISS-lEAc',
      // Randy Travis — Forever And Ever, Amen  ·  "Randy Travis - Forever and Ever, Amen (Official Audio)" [Randy Travis]
      'KtKXc_v2iLE',
      // Alan Jackson — Chattahoochee  ·  "Chattahoochee" [Alan Jackson - Topic]
      '9kkDgx01aHc',
      // Garth Brooks — Friends In Low Places  ·  "Friends in Low Places" [Garth Brooks Tribute - Topic]
      'tK-hW-uESJI',
      // Shania Twain — Man! I Feel Like A Woman!  ·  "Man! I Feel Like A Woman!" [Shania Twain - Topic]
      'o9OUSh_ADJ0',
      // The Chicks — Wide Open Spaces  ·  "Wide Open Spaces (Album Version)" [The Chicks - Topic]
      'wue1IQG8IL8',
      // Emmylou Harris — Boulder To Birmingham  ·  "Boulder to Birmingham (2003 Remaster)" [Emmylou Harris - Topic]
      'JjLx7ESHRcA',
      // Loretta Lynn — Coal Miner’s Daughter  ·  "Coal Miner's Daughter (Single Version)" [Loretta Lynn - Topic]
      'zoKThsOCjuU',
      // Glen Campbell — Wichita Lineman  ·  "Wichita Lineman (Remastered 2001)" [Glen Campbell - Topic]
      'Q8P_xTBpAcY',
      // Kenny Rogers — The Gambler  ·  "The Gambler (Remastered 2006)" [Kenny Rogers - Topic]
      'ngPG01UREb4',
      // Charley Pride — Kiss An Angel Good Mornin’  ·  "Kiss an Angel Good Mornin'" [Charley Pride - Topic]
      'Mo-ofNvl-fM',
      // Hank Williams — Your Cheatin’ Heart  ·  "Your Cheatin’ Heart" [Hank Williams - Topic]
      'UxlmdknsB5M',
      // Tanya Tucker — Delta Dawn  ·  "Delta Dawn" [Tanya Tucker - Topic]
      'g6ymXTFFtnc',
      // Conway Twitty — Hello Darlin’  ·  "Hello Darlin' (Re-Recorded In Stereo)" [Conway Twitty - Topic]
      'NKAuTM6APuE',
      // Don Williams — Tulsa Time  ·  "Tulsa Time" [Don Williams - Topic]
      'oI6c9qpYKPU',
      // Marty Robbins — El Paso  ·  "El Paso (Album Version)" [Marty Robbins - Topic]
      'EIZT7rsZJs8',
      // Crystal Gayle — Don’t It Make My Brown Eyes Blue  ·  "Don't It Make My Brown Eyes Blue" [Crystal Gayle - Topic]
      'uLdB7-N3A3Q',
      // Ronnie Milsap — Smoky Mountain Rain  ·  "Smoky Mountain Rain" [Ronnie Milsap - Topic]
      'Zj6_CpSGPoE',
      // Eddie Rabbitt — I Love A Rainy Night  ·  "I Love a Rainy Night (2009 Remaster)" [Eddie Rabbitt - Topic]
      'NWoL65SexB4',
      // Barbara Mandrell — Sleeping Single In A Double Bed  ·  "Sleeping Single in a Double Bed" [Release - Topic]
      'akrnhXl_U4M',
      // Gene Watson — Farewell Party  ·  "Farewell Party (Digitally Enhanced Remastered Recording)" [Gene Watson - Topic]
      'YTI9TYDMRFE',
      // Ricky Skaggs — Highway 40 Blues  ·  "Highway 40 Blues (Album Version)" [Ricky Skaggs - Topic]
      'cJEdmDcWk34',
    ],
  },
  {
    id: 'hotcountry',
    label: 'HOT COUNTRY',
    covers: ['Hot Country'],
    tracks: [
      // Morgan Wallen — Wasted On You  ·  "Morgan Wallen – Wasted On You (Audio Only)" [Morgan Wallen]
      'KE35_SlTdn4',
      // Kacey Musgraves — Space Cowboy  ·  "Space Cowboy" [Release - Topic]
      '8wMOZleW9CI',
      // Miranda Lambert — The House That Built Me  ·  "The House That Built Me" [Release - Topic]
      'Npidcpl8naQ',
      // Zach Bryan — Something in the Orange  ·  "Zach Bryan - Something In The Orange" [Zach Bryan]
      'lA8F9sIhGdg',
      // Lainey Wilson — Things A Man Oughta Know  ·  "Lainey Wilson - Things A Man Oughta Know (Official Audio)" [Lainey Wilson]
      'fwgjXr3hzNg',
      // Jason Aldean — Dirt Road Anthem  ·  "Jason Aldean - Dirt Road Anthem (Official Audio)" [Jason Aldean]
      'dPkzzAeUQ7s',
      // Carrie Underwood — Before He Cheats  ·  "Before He Cheats" [Carrie Underwood - Topic]
      'bM9M8f26s3Q',
      // Blake Shelton — God Gave Me You  ·  "Blake Shelton - "God Gave Me You" - First Look" [Blake Shelton]
      'J0f2fg_zmJI',
      // Dierks Bentley — Drunk On A Plane  ·  "Drunk on a Plane" [Release - Topic]
      'uBtZYz7Gzd4',
      // Kelsea Ballerini — Peter Pan  ·  "Kelsea Ballerini - Peter Pan (Official Audio)" [Kelsea Ballerini]
      'ja0pKS7KKss',
      // Cole Swindell — She Had Me At Heads Carolina  ·  "Cole Swindell - She Had Me At Heads Carolina (Audio)" [Cole Swindell]
      '446TNAxwg_g',
      // Tyler Childers — Feathered Indians  ·  "Feathered Indians" [Tyler Childers - Topic]
      'j-lwWgYLb68',
      // Jon Pardi — Dirt On My Boots  ·  "Dirt on My Boots" [Release - Topic]
      'mCPIOs-y9DY',
      // Chris Young — Gettin’ You Home  ·  "Chris Young - Songwriting - "Gettin' You Home"" [Chris Young]
      'afaBPcgMRdc',
      // Riley Green — There Was This Girl  ·  "Riley Green - "There Was This Girl" (Official Audio)" [Riley Green]
      'C8GZAtSqH2w',
      // Dustin Lynch — Small Town Boy  ·  "Dustin Lynch - Small Town Boy (Official Audio)" [Dustin Lynch]
      'BSDxUVZJwTg',
      // Russell Dickerson — Yours  ·  "Yours" [Russell Dickerson - Topic]
      'OxFnqgXTSbc',
    ],
  },
  {
    id: 'top100',
    label: 'TOP 100',
    covers: ['Top 100'],
    tracks: [
      // Dua Lipa — Levitating  ·  "Dua Lipa - ‘Levitating’ at the AMAs 2020" [Dua Lipa]
      '57bNHupO3MU',
      // Olivia Rodrigo — drivers license  ·  "drivers license" [Olivia Rodrigo - Topic]
      'tNJhkrpLGT8',
      // Taylor Swift — Anti-Hero  ·  "Anti-Hero" [Taylor Swift - Topic]
      'N2ucWOw-v0c',
      // Sam Smith — Stay With Me  ·  "Stay With Me (Radio Edit)" [Sam Smith - Topic]
      'nLQFBq9ykjI',
      // Glass Animals — Heat Waves  ·  "Heat Waves" [Glass Animals - Topic]
      'pzeefqfSMjY',
      // Lizzo — About Damn Time  ·  "About Damn Time" [Lizzo - Topic]
      'tRQe3HjZEzw',
      // Doja Cat — Paint The Town Red  ·  "Paint The Town Red" [Doja Cat - Topic]
      'fGe8drSjqHI',
      // Post Malone — Circles  ·  "Post Malone - Circles (Official Audio)" [Post Malone]
      'pQV0WEdT_OE',
      // Ed Sheeran — Perfect  ·  "Ed Sheeran - Perfect Duet (with Beyoncé) [Official Audio]" [Ed Sheeran]
      '817P8W8-mGE',
      // Ariana Grande — 7 rings  ·  "Ariana Grande - 7 rings (Official Audio)" [Ariana Grande]
      'BMA8w5BHC98',
      // Coldplay — Higher Power  ·  "Coldplay - Higher Power (Official Audio // Extraterrestrial Transmission)" [Coldplay]
      'gXgf5smLEgQ',
      // Halsey — Graveyard  ·  "Halsey - Graveyard (Audio)" [HALSEY]
      '2CVX9NQ9AU4',
      // Shakira — Hips Don’t Lie  ·  "Hips Don't Lie" [Shakira - Topic]
      '6Tj4DsgJC4Q',
      // Teddy Swims — Lose Control  ·  "Lose Control (Radio Edit)" [Teddy Swims - Topic]
      'mOAy_vCa33E',
      // Gracie Abrams — Close To You  ·  "Gracie Abrams - Close To You (Audio)" [Gracie Abrams Fan]
      'z9PEBMB43mw',
      // Sabrina Carpenter — Espresso  ·  "Sabrina Carpenter - Espresso (Official Audio)" [Sabrina Carpenter]
      '51zjlMhdSTE',
      // Benson Boone — Beautiful Things  ·  "Benson Boone - Beautiful Things (Acoustic) [Official Audio]" [Benson Boone]
      '_T2ydRYLt-U',
      // Djo — End Of Beginning  ·  "Djo - End Of Beginning (Official Audio)" [Djo Music]
      'xy3AcmW0lrQ',
    ],
  },
];

export const STATION_BY_ID = Object.fromEntries(YT_STATIONS.map((s) => [s.id, s]));

/** The station a first-time visitor hears. */
export const DEFAULT_STATION = (YT_STATIONS.find((s) => s.isDefault) ?? YT_STATIONS[0]).id;

/** Every category the dial claims to cover, for the settings copy and QA. */
export const COVERED = YT_STATIONS.flatMap((s) => s.covers);
