// YOUTUBE STATIONS — the dial.
//
// GENERATED by scripts/radio-curate.mjs. Do not hand-edit: re-run the script,
// which re-verifies every entry and rewrites this file.
//
// Last verified: 2026-08-24
//
// Every playlist here passed four checks, not one: it resolves through the
// official oEmbed endpoint, its title matches the genre it is filed under, it
// holds at least 15 tracks, and a sample of those tracks are
// INDIVIDUALLY embeddable. That last check is the one that matters — a
// playlist full of embed-blocked videos passes every other test and then
// plays silence.
//
// These are third-party playlists reached through the official IFrame Player
// API. Nothing is downloaded, extracted, cached or bundled; YouTube serves the
// audio and counts the view exactly as an embed on any web page does. Each
// station carries several candidates so one going private degrades to the next.
//
// BLOCKBUSTER THROWBACK is the store's own identity station and the default.
// The name is nostalgic flavour for a video-rental-era shop; it does NOT imply
// any affiliation with, or endorsement by, Blockbuster or these channels.
export const YT_STATIONS = [
  {
    id: 'blockbuster',
    label: '★ BLOCKBUSTER THROWBACK',
    isDefault: true,
    // 80s AND 90s, WHICH IS WHAT THE STATION SAYS IT IS.
    //
    // It used to also carry "Mtv Hits 90's-2000's", "Late 2000s / early 2010s"
    // and "Early 2000's Throwbacks" — one of which THROWBACKS carries too.
    // That is why the two stations sounded like the same station: the house
    // station had quietly become a superset of the one next to it. The 2000s
    // entries are gone from here and stay on THROWBACKS, where they belong.
    //
    // A "Most Popular Music VIDEOS" compilation went with them. A video
    // compilation is not a music playlist: the audio carries intros, skits and
    // the sound effects of whatever is on screen, which is what "I hear cars
    // and gunshots" was. Anything whose own title says videos is not a
    // candidate for a station meant to sit in the background of a shop.
    covers: ['80s', '90s', 'MTV-era'],
    playlists: [
      // 80s Music Hits | Best 80s Music Playlist — RHINO (100 tracks, 100% embeddable)
      'PLmXxqSJJq-yXrCPGIT2gn8b34JjOrl4Xf',
      // 80s Hard Rock Playlist | 80s Hard Rock & Hair Metal Hits — RHINO (100 tracks, 100% embeddable)
      'PLmXxqSJJq-yVWpRFGImHYZBQTuBGLjG4t',
      // 80s Rock Hits Music Playlist - Greatest 1980\'s Rock Songs — Redlist Decades (98 tracks, 100% embeddable)
      'PLGBuKfnErZlDbjq8T1TA4mHjIaLf77iBO',
      // 90s R&B Hits | 90s R&B Playlist — RHINO (100 tracks, 100% embeddable)
      'PLmXxqSJJq-yXJWtyopwsEEqoSNapmeOFh',
      // 90s r&b and hip hop hits — Brittany Herndon (100 tracks, 100% embeddable)
      'PL9ADD7GKlxvEfDKWmW93kv92Gh9L1s0FF',
      // 90s Hip Hop Playlist - The Best 90s Rap Songs — Revive Music (98 tracks, 100% embeddable)
      'PLxA687tYuMWgEVasBziZoZ1Bk7JLnu-Rf',
      // 90s Rap Music Hits Playlist - Greatest 1990\'s Rap Songs — Redlist Decades (100 tracks, 100% embeddable)
      'PLGBuKfnErZlDSR8vN4nse7MI_bQqYvopq',
      // 90s Pop Music Hits Playlist - Greatest 1990\'s Pop Songs — Redlist Decades (98 tracks, 100% embeddable)
      'PLGBuKfnErZlAH3yaYBpIXra0HxFGEJKsB',
    ],
  },
  {
    id: 'chillrnb',
    label: 'CHILL R&B',
    covers: ['Chill R&B'],
    playlists: [
      // Chill R&B Music Playlist | Drake + SZA + Post Malone + Brent Fai — Kaelah McIntosh (41 tracks, 100% embeddable)
      'PL08ytyBKu7cp10v7cIdGkwLGk6sb_Vcw-',
      // chill music r&b for a shower — נתנאל בן נתן (39 tracks, 100% embeddable)
      'PLfIFsYoouyQv8oDu83YdCXwMu3tEI5bfa',
      // R&B Favorites 90s-2000s- Slow Jams — E (100 tracks, 100% embeddable)
      'PLaecGJ-Zm9QOJx1TxfIjJzksWWUrz5wl-',
      // Dark R&B for Late Nights -  RnB Soul Chill Mix — Late Night Dreams (40 tracks, 100% embeddable)
      'PLp0wlPvpeRs60I7C_0M0akuTJsPIp02PJ',
    ],
  },
  {
    id: 'rnb',
    label: 'R&B',
    covers: ['R&B'],
    playlists: [
      // Best Of R&B MIX 90s 2000s - 2023 | Rihanna, Usher, Chris Brown,  — R&B Hit  (91 tracks, 100% embeddable)
      'PLKTP4Gcm8E4Z1dlZuBHP-W94yN3kqR3t0',
      // Best R&B Soul Songs of All Time - Classic R&B Music Playlist Upd — Redlist - Favorite Music (98 tracks, 100% embeddable)
      'PLi13rLFLL6Q8h6kbXHkXIKJJn9IX5Qtx5',
      // Sunday Soul Sessions — Happy Ngwenya (45 tracks, 100% embeddable)
      'PL_wH8SqwOLO57UnJ5p26Utf1c2dByY9uv',
      // 80s R&B/Soul Grooves: The Best of | Hits & More — RomainDiscoSoul Music (99 tracks, 100% embeddable)
      'PLYZ_UlyizlENy7I5TH2cgpzD4eIR8_jsn',
    ],
  },
  {
    id: 'hiphop',
    label: 'HIP-HOP',
    covers: ['Hip-Hop'],
    playlists: [
      // Hip Hop 2026 - Rap Playlist - Hip Hop Mix & Rap Mix 2026 — Chillax (100 tracks, 100% embeddable)
      'PLDIoUOhQQPlXFSnCfj8HuVhOUSC0QwxYD',
      // 2000s Hip Hop R&B - Top Hip Hop and R&B Songs 2000s (Playlist Up — Best playlists by Jim Music For You (100 tracks, 100% embeddable)
      'PLm90DCMQmtllGPVGffVk5kqNCIdRsi3q9',
      // Clean Rap Playlist 2026 - Clean Hip Hop - Clean Rap & Rap Songs — Lit Trending Music (100 tracks, 100% embeddable)
      'PLO7-VO1D0_6NqQTF1PDqVuSRs70XniNDq',
      // 90s Hip Hop Playlist - The Best 90s Rap Songs — Revive Music (98 tracks, 100% embeddable)
      'PLxA687tYuMWgEVasBziZoZ1Bk7JLnu-Rf',
    ],
  },
  {
    id: 'rap',
    label: 'RAP',
    covers: ['Rap'],
    playlists: [
      // Hip Hop 2026 - Rap Playlist - Hip Hop Mix & Rap Mix 2026 — Chillax (100 tracks, 100% embeddable)
      'PLDIoUOhQQPlXFSnCfj8HuVhOUSC0QwxYD',
      // Rap Hits 2010-2024 — Vanessa Neves (99 tracks, 100% embeddable)
      'PLob0npZw9QXGjUkWeOj816g5jNMwQgs_X',
      // Rap Playlist 2026 - Best Rap Songs - Rap 2026 & Top Rap Songs — AT Charts (100 tracks, 100% embeddable)
      'PL3-sRm8xAzY9Qd1BoHHYFXRMUQlB4BZNt',
      // Rap Playlist #1🍎2016-2020 — Landon Cantrell (100 tracks, 100% embeddable)
      'PLewRfm_YlyuH6gtZWAqOIVOYgC0zKeKLM',
    ],
  },
  {
    id: 'country',
    label: 'COUNTRY',
    covers: ['Country'],
    playlists: [
      // Country Music Playlist 2026 ♫ Top Country Songs of 2026 (Best Co — Redlist - Biggest Songs (79 tracks, 100% embeddable)
      'PL3oW2tjiIxvRDymF6SFf7t4xfDbtRQxlt',
      // Best Country Songs of All Time - Top Country Music Videos — Redlist - Biggest Songs (100 tracks, 100% embeddable)
      'PL3oW2tjiIxvQW6c-4Iry8Bpp3QId40S5S',
      // Country Music Playlist 2018-2026: Best Country Songs — Ryan Robinette (99 tracks, 100% embeddable)
      'PLN_YZjgdIDCfYxxFZW4TFKiFNraH6d9hK',
      // Country Music Playlist 2026 - Top Country Songs 2024 2025 2026 — Revive Music (99 tracks, 100% embeddable)
      'PLxA687tYuMWi6vOzsNdoOZdcN2W5MwsLq',
    ],
  },
  {
    id: 'hotcountry',
    label: 'HOT COUNTRY',
    covers: ['Hot Country'],
    playlists: [
      // Billboard Hottest Country Songs 2026 PLAYLIST — Hight Quality Music (98 tracks, 100% embeddable)
      'PLi7ihgkEws7RB7W89lEjK2qvItmbyLBLl',
      // Today\'s Country Music Hits — Vevo Playlists (50 tracks, 100% embeddable)
      'PLkqz3S84Tw-Ts6lXxVUmUGrDf4EgE2BHT',
      // Country Music Playlist 2026 ♫ Top Country Songs of 2026 (Best Co — Redlist - Biggest Songs (79 tracks, 100% embeddable)
      'PL3oW2tjiIxvRDymF6SFf7t4xfDbtRQxlt',
      // Best Country Songs of All Time - Top Country Music Videos — Redlist - Biggest Songs (100 tracks, 100% embeddable)
      'PL3oW2tjiIxvQW6c-4Iry8Bpp3QId40S5S',
    ],
  },
  {
    id: 'pop',
    label: 'POP',
    covers: ['Pop'],
    playlists: [
      // New Pop Songs 2026 - Pop Music 2026 - New Pop & Pop Songs — Chillax (100 tracks, 100% embeddable)
      'PLDIoUOhQQPlUDNpjEYTTE9tb-QvUHUSMt',
      // Pop Music Playlist 2026 - Pop Playlist - Pop Songs 2026 - Pop Mu — Roses are Red (100 tracks, 100% embeddable)
      'PLcirGkCPmbmHk1eaOH0C9PBETFZjEPVNu',
      // Clean Pop Music Playlist 2024 – Fresh Hits & Party Anthems — Purrfect Playlist (48 tracks, 100% embeddable)
      'PLEPQby6_o7m1S4DslnGam71gNt4bgPqCE',
      // Clean Classroom Playlist - Clean Pop Hits - Clean Pop Songs 2025 — Revive Music (97 tracks, 100% embeddable)
      'PLxA687tYuMWiQgWkVUG6164xRGqPk9Vr2',
    ],
  },
  {
    id: 'top100',
    label: 'TOP 100',
    covers: ['Top 100'],
    playlists: [
      // Top 100 Songs 2026 - Billboard 2026 - Top 100 & Top Hits — Chillax (100 tracks, 100% embeddable)
      'PLDIoUOhQQPlWc-Kd6TCjTRIl0Z6fSQV0X',
      // Top 100 Songs 2026 - Hot Hits & Top Hits - Top Hits 2026 Playlis — #MusicPlaylist LIT (100 tracks, 100% embeddable)
      'PLHg022HMFzFCJNn0WN7UM0_0uY109bcv2',
      // TOP 100 Most Streamed Songs of all time on Spotify (Update/every — ESC Cyprus (99 tracks, 100% embeddable)
      'PLhNyfL3WbvS3RpbQm1eMWFLPEu6BcY166',
      // Top Songs 2026 - Playlist 2026 - Top Hits & Music 2026 — Chillax (100 tracks, 100% embeddable)
      'PLDIoUOhQQPlXr63I_vwF9GD8sAKh77dWU',
    ],
  },
  {
    id: 'throwback',
    label: 'THROWBACKS',
    covers: ['Throwbacks', '2000s', '2010s'],
    // CLEAN CUTS ONLY, AND HERE IS THE LIMIT OF THAT PROMISE.
    //
    // This station was reported as playing gunshots and car engines. That is
    // not noise in the stream: on YouTube the popular version of a 2000s track
    // is the OFFICIAL MUSIC VIDEO, and those open with skits — dialogue, tyres,
    // shots — before the song starts. A store speaker playing film-set foley
    // between songs is exactly wrong for this room.
    //
    // The two general "throwback songs" playlists here were compilations of
    // those videos, and they are gone. What is left is the two explicitly CLEAN
    // uploads, which are radio edits and carry no video intros. 90 tracks.
    //
    // The honest caveat, because it should be written down rather than implied:
    // the ingest verifies that a playlist is EMBEDDABLE, not what it sounds
    // like. Nothing in this repo has ever listened to these. Picking by the
    // word "Clean" in the title is a judgement, not a measurement, and if
    // something still opens with a skit that is why.
    playlists: [
      // 2000s & 2010s Playlist - Clean — Alison English (43 tracks, 100% embeddable)
      'PLmRza01gbTgIyEmE20AH0FpqftgAcbttZ',
      // 2010s music (Clean Version) — Johnathon Baker (47 tracks, 100% embeddable)
      'PLPEj0tTK7m0huBYSP5aFbGLH4H1yqOFJd',
    ],
  },
  {
    id: 'party',
    label: 'PARTY',
    covers: ['Party'],
    playlists: [
      // The Top 100 Best Party Songs of All Time — C Sebastian (90 tracks, 100% embeddable)
      'PL10BZg10BCDQxKXg0qN_-Y6RwvfdDvJdy',
      // PARTY 2000 2010 🔥 Nostalgia Pop Top Hits Dance Radio Summer Mus — Samuel Vasconcelos (73 tracks, 100% embeddable)
      'PLDEoYTx7cT4dC7dkTTYi1exK5iYVtBw0B',
      // Clean Pop Music Playlist 2024 – Fresh Hits & Party Anthems — Purrfect Playlist (48 tracks, 100% embeddable)
      'PLEPQby6_o7m1S4DslnGam71gNt4bgPqCE',
      // Pride Party Playlist — Ron. Will (83 tracks, 100% embeddable)
      'PLd7hYqiihoP33TLNR7TKMqguAVH1YGmCn',
    ],
  },
];

export const STATION_BY_ID = Object.fromEntries(YT_STATIONS.map((s) => [s.id, s]));

/** The station a first-time visitor hears. */
export const DEFAULT_STATION = (YT_STATIONS.find((s) => s.isDefault) ?? YT_STATIONS[0]).id;

/** Every category the dial claims to cover, for the settings copy and QA. */
export const COVERED = YT_STATIONS.flatMap((s) => s.covers);
